name: CI for My Project

on:
  push:
    branches: [ master ]  # Trigger on push to master; change if you use a different branch like 'main'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Echo a Message
      run: echo "Hello, world!"
